NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),

]

news/urls.py
from allauth.account.views import ConfirmEmailView
from django.urls import path, include
from . import views
from .views import (
    NewsListView,
    NewsDetailView,
    SearchView,
    SearchResultView,
    CustomSignupView,
    LoginView,
    NewsCreateView,
    NewsUpdateView,
    NewsDeleteView,
    become_author,
    UserUpdateView,
)


app_name = 'news'

urlpatterns = [
    path('accounts/signup/', CustomSignupView.as_view(), name='account_signup'),
    path('accounts/login/', LoginView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('', NewsListView.as_view(), name='news_list'),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('search/results/', SearchResultView.as_view(), name='search_results'),
    path('news/create/', NewsCreateView.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='news_edit'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
    path('become_author/', become_author, name='become_author'),
    path('access_denied/', views.access_denied, name='access_denied'),
    path('profile/update/', UserUpdateView.as_view(), name='profile_update'),
    path('category/toggle_subscription/<int:category_id>/<int:subscribed>/', views.toggle_category_subscription,
         name='toggle_category_subscription'),
]

news/models.py
from django.core.mail import send_mail
from django.contrib.auth.models import Group
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.dispatch import Signal


post_save_news = Signal()


# Handler for the signal
def post_save_news_handler(sender, instance, created, send_notification_to_subscribers=None, **kwargs):
    if created and instance.post_type == 'news':

        # Your code to send notifications to subscribers
        send_notification_to_subscribers.delay(instance.pk)


# Connect the handler to the signal
post_save_news.connect(post_save_news_handler, sender='news.Post')


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        post_comments_rating = self.posts.aggregate(models.Sum('comments__rating')).get('comments__rating__sum') or 0
        self.rating = (self.posts.aggregate(models.Sum('rating')).get('rating__sum') or 0) * 3
        self.rating += post_comments_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, related_name='subscribed_categories', blank=True)
    posts = models.ManyToManyField('Post', through='PostCategory')
    def __str__(self):
        return self.name

class PostManager(models.Manager):
    def get_queryset(self):
        return super(PostManager, self).get_queryset().filter(post_type='news')


class Post(models.Model):
    POST_TYPES = [
        ('Article', 'Article'),
        ('News', 'News'),
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    post_type = models.CharField(max_length=10, choices=POST_TYPES)
    created_date = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...' if len(self.text) > 124 else self.text


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('post', 'category')

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

@receiver(post_save, sender=User)
def add_user_to_common_group(sender, instance, created, **kwargs):
    if created:
        common_group = Group.objects.get(name='common')
        instance.groups.add(common_group)

news/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):
    #description = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = ['id','author', 'title', 'content']

news/views.py
import ssl
from smtplib import SMTP_SSL

from allauth.account.views import SignupView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView as AuthLoginView
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView, ListView

from .forms import PostForm
from .models import Post, Group, Category

from django.utils.translation import gettext_lazy as _
from django.dispatch import Signal
from .tasks import send_notification_to_subscribers

post_save_news = Signal()
class NewsListView(ListView):
    model = Post
    template_name = 'news/news_list.html'
    context_object_name = 'news'
    ordering = ['-created_at']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)

        paginator = context['paginator']
        current_page = self.request.GET.get('page', 1)
        news = paginator.get_page(current_page)

        start_range = max(news.number - 5, 1)
        end_range = min(news.number + 4, paginator.num_pages)

        context['news'] = news
        context['paginator'] = paginator
        context['start_range'] = start_range
        context['end_range'] = end_range
        context['current_page'] = news.number
        context['news_count'] = Post.objects.filter(post_type='news').count()
        context['is_common_user'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class NewsDetailView(DetailView):
    model = Post
    template_name = 'news/news_detail.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super(NewsDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            news = self.get_object()
            context['category_subscribed'] = \
                (self.request.user.subscribed_categories.filter(pk__in=news.categories.all()).exists())
        return context


class SearchView(ListView):
    model = Post
    template_name = 'news/search.html'
    context_object_name = 'search_results'

    def get_queryset(self):
        return Post.objects.all()


class SearchResultView(ListView):
    model = Post
    template_name = 'news/search_results.html'
    context_object_name = 'search_results'
    paginate_by = 10

    def get_queryset(self):
        query_title = self.request.GET.get('title')
        query_author = self.request.GET.get('author')
        query_date = self.request.GET.get('date')

        queryset = Post.objects.all()

        if query_title:
            queryset = queryset.filter(title__icontains=query_title)

        if query_author:
            queryset = queryset.filter(author__username__icontains=query_author)

        if query_date:
            queryset = queryset.filter(created_at__gte=query_date)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchResultView, self).get_context_data(**kwargs)
        search_results = context['search_results']

        paginator = Paginator(search_results, self.paginate_by)
        current_page = self.request.GET.get('page', 1)
        search_results = paginator.get_page(current_page)

        start_range = max(search_results.number - 5, 1)
        end_range = min(search_results.number + 4, paginator.num_pages)

        context['search_results'] = search_results
        context['paginator'] = paginator
        context['start_range'] = start_range
        context['end_range'] = end_range
        context['current_page'] = search_results.number

        return context


class CustomSignupView(SignupView):
    template_name = 'account/signup.html'
    success_url = reverse_lazy('account_login')


class LoginView(AuthLoginView):
    template_name = 'account/login.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'email']
    template_name = 'user_update.html'
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user


class NewsCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    template_name = 'news/news_create.html'
    form_class = PostForm
    success_url = reverse_lazy('news:news_list')
    context_object_name = 'news'

    def form_valid(self, form):
        # Set author and post_type
        form.instance.author = self.request.user
        form.instance.post_type = 'news'

        today = timezone.now().date()
        user = self.request.user

        # Count the number of articles the user has published today
        num_news_today = Post.objects.filter(author=user, created_at__date=today).count()

        # Check if the limit is reached (3 articles per day)
        if num_news_today >= 3:
            raise ValidationError("Вы не можете публиковать больше трёх новостей в день!.")

        # Set author and post_type
        form.instance.author = user
        form.instance.post_type = 'news'

        # Save the post
        response = super().form_valid(form)

        # Generate email content
        email_html_content = generate_email_content(form.instance)
        email_subject = f'Новая новость: {form.instance.title}'

        # Formulate the email message
        username = self.request.user.username
        news_url = self.request.build_absolute_uri(form.instance.get_absolute_url())
        email_message = f'Здравствуйте, {username}. Новая статья в твоём любимом разделе!'
        email_message += f'<br><a href="{news_url}">Перейти к статье</a><br>'
        email_message += email_html_content

        # Create an SSL connection to the SMTP server
        context = ssl.create_default_context()
        server = SMTP_SSL('smtp.yandex.ru', 465, context=context)

        try:
            # Send the email
            send_mail(email_subject, '', 'projectnewspaper1@yandex.ru',
                      [self.request.user.email], html_message=email_message)

        finally:
            server.quit()

        return response

    def test_func(self):
        return self.request.user.groups.filter(name='authors').exists()


class NewsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'news/news_edit.html'
    form_class = PostForm
    context_object_name = 'news'
    success_url = reverse_lazy('news:news_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post_type = 'news'
        email_html_content = generate_email_content(form.instance)
        email_subject = f'Обновление новости: {form.instance.title}'
        username = self.request.user.username
        news_url = self.request.build_absolute_uri(form.instance.get_absolute_url())
        email_message = f'Здравствуйте, {username}. Новость в вашей любимой категории обновлена!'
        email_message += f'<br><a href="{news_url}">Перейти к новости</a><br>'
        email_message += email_html_content

        context = ssl.create_default_context()
        server = SMTP_SSL('smtp.yandex.ru', 465, context=context)

        try:
            send_mail(email_subject, '', 'projectnewspaper1@yandex.ru',
                      [self.request.user.email], html_message=email_message)
            return super(NewsUpdateView, self).form_valid(form)
        finally:
            server.quit()

    def test_func(self):
        return self.request.user.groups.filter(name='authors').exists()


class NewsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'news/news_delete.html'
    context_object_name = 'news'
    success_url = reverse_lazy('news:news_list')

    def test_func(self):
        return self.request.user.groups.filter(name='authors').exists()


@login_required
def become_author(request):
    user = request.user
    author_group = Group.objects.get(name='authors')
    user.groups.add(author_group)
    return redirect('news:news_list')


def access_denied(request):
    return render(request, 'news/access_denied.html')


@login_required
def toggle_category_subscription(request, category_id, subscribed):
    category = get_object_or_404(Category, id=category_id)
    user = request.user

    if subscribed == 1:
        category.subscribers.add(user)
    else:
        category.subscribers.remove(user)

        category.subscribers.remove(user)

        category.subscribers.remove(user)

    return JsonResponse({'subscribed': category.subscribers.filter(id=user.id).exists()})


def generate_email_content(post):
    html_content = f'<h1>{post.title}</h1>'
    html_content += f'<p>Содержимое новости:{post.content[:50]}</p>'
    return html_content

templates/news/access_denied.html
{% extends 'news/default.html' %}

<h1>Доступ запрещен</h1>
<p>Создавать, редактировать и удалять статьи/новости могут только авторы.</p>
<a href="{% url 'news:become_author' %}">Стать автором</a>

templates/news/become_author.html
{% extends 'news/default.html' %}

{% block content %}
<h2>Стать автором</h2>
<p>Вы можете стать автором и получить права на создание, редактирование и удаление статей/новостей.</p>
<form action="{% url 'news:become_author' %}" method="post">
  {% csrf_token %}
  <button type="submit">Стать автором</button>
</form>
{% endblock %}

templates/news/default.html
{% load static %}
{% load censor %}
{% load censor custom_tags %}



<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{% block title %}News Portal{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <header>
            <h1>News Portal</h1>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'news:news_list' %}">Список новостей</a></li>
                {% if user.is_authenticated %}
                    <p>Hello, {{ user.username }}!</p>
                    <a href="{% url 'account_logout' %}">Logout</a>
                {% else %}
                    <p>You are not logged in.</p>
                    <a href="{% url 'account_login' %}">Login</a>
                {% endif %}
            </ul>
        </nav>
        <main>
            {% block content %}
            {% endblock %}

            <!-- Постраничная навигация -->
            {% if news.has_previous or news.has_next %}
                <div class="pagination">
                    {% if news.has_previous %}
                        <a href="?page=1">Первая</a>
                        <a href="?page={{ news.previous_page_number }}">Предыдущая</a>
                    {% endif %}
                    {% for page_num in news.paginator.page_range %}
                        {% if news.number == page_num %}
                            <span class="current-page">{{ page_num }}</span>
                        {% else %}
                            <a href="?page={{ page_num }}">{{ page_num }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if news.has_next %}
                        <a href="?page={{ news.next_page_number }}">Следующая</a>
                        <a href="?page={{ news.paginator.num_pages }}">Последняя</a>
                    {% endif %}
                </div>
            {% endif %}

        </main>
        <footer>
            <p>&copy; 2023 News Portal. All rights reserved.</p>
        </footer>
    </div>
</body>
</html>

templates/news/news_create.html
{% extends 'news/default.html' %}

{% load static %}
{% load censor %}
{% load censor custom_tags %}

{% block title %}Создание новости/статьи{% endblock %}

{% block content %}
    <h2>Создание новости</h2>
    <!-- Форма создания новости -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать новость</button>
    </form>

    {% if user|user_belongs_to_group:'common' %}
    <p>Создавать, редактировать и удалять статьи/новости могут только авторы.</p>
    <a href="{% url 'news:become_author' %}">Стать автором</a>
    {% endif %}

    {% if is_common_user %}
    <p>Создавать, редактировать и удалять статьи/новости могут только авторы.</p>
    <a href="{% url 'news:become_author' %}">Стать автором</a>
    {% endif %}

{% endblock %}

templates/news/news_delete.html
{% extends 'news/default.html' %}

{% block title %}Удаление новости/статьи{% endblock %}

{% block content %}
    <h2>Удаление новости</h2>
    <p>Вы действительно хотите удалить новость/статью "{{ post.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
        <a href="{% url 'news:news_detail' pk=news.pk %}">Отмена</a>
    </form>
{% endblock %}

templates/news/news_detail.html
{% extends 'news/default.html' %}

{% load censor %}

{% block title %}Детали новости{% endblock %}

<a href="{% url 'news:news_create' %}">Добавить новость</a>

{% block content %}
    <h2>{{ news.title|censor }}</h2>
    <p>Автор: {{ news.author.username }}</p>
    <p>{{ news.created_at|date:"d.m.Y" }}</p>
    <p>Рейтинг: {{ news.rating }}</p>
    <p>Категории:
        {% for category in news.categories.all %}
            <span>{{ category.name }}</span>
            {% if category_subscribed %}
                <a href="{% url 'news:toggle_category_subscription' category.id 0 %}">Отписаться</a>
            {% else %}
                <a href="{% url 'news:toggle_category_subscription' category.id 1 %}">Подписаться</a>
            {% endif %}
        {% endfor %}
    </p>
    <p>{{ news.content|censor }}</p>

    <a href="{% url 'news:news_edit' pk=news.pk %}">Редактировать</a>
    <a href="{% url 'news:news_delete' pk=news.pk %}">Удалить</a>

{% endblock %}

templates/news/news_edit.html
{% extends 'news/default.html' %}

{% block title %}Редактирование новости/статьи{% endblock %}

{% block content %}
    <h2>Редактирование</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

templates/news/news_list.html
% extends 'news/default.html' %}
{% load censor %}
{% load censor custom_tags %}

{% block title %}Список новостей{% endblock %}

{% block content %}
    <a href="{% url 'news:search' %}">Поиск</a>
    <a href="{% url 'news:news_create' %}">Добавить новость</a>
    {% if user.is_authenticated %}
        <a href="{% url 'account_logout' %}?next=/news">Выйти</a>
    {% else %}
        <a href="{% url 'account_login' %}?next=/news">Войти</a>
        <a href="{% url 'account_signup' %}?next=/news">Зарегистрироваться</a>
    {% endif %}
    {% if user|user_belongs_to_group:'common' %}
        <a href="{% url 'news:become_author' %}">Стать автором</a>
    {% endif %}

    <h2>Список новостей</h2>
    <p>Количество новостей: {{ news_count }}</p>
    <ul>
        {% for post in news %}
            <li>
                <h3><a href="{% url 'news:news_detail' post.id %}">{{ post.title|censor }}</a></h3>
                <p>{{ post.created_at|date:"d.m.Y" }}</p>
                <p>Рейтинг: {{ post.rating }}</p>
                <p>Категории:
                    {% for category in post.categories.all %}
                        <span>{{ category.name }}</span>
                    {% endfor %}
                </p>
                <p>{{ post.content|censor|truncatechars:20 }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/news/search.html
{% extends 'news/default.html' %}

{% block title %}Поиск новостей{% endblock %}

{% block content %}
    <h2>Поиск новостей</h2>
    <form method="GET" action="{% url 'news:search_results' %}">
        <label for="search_title">Название:</label>
        <input type="text" name="title" id="search_title">
        <br>
        <label for="author">Автор:</label>
        <input type="text" name="author" id="author">
        <br>
        <label for="date">Дата публикации позже:</label>
        <input type="date" name="date" id="date">
        <br>
        <input type="submit" value="Искать">
    </form>
{% endblock %}

templates/news/search_results.html
{% extends 'news/default.html' %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
    <h2>Результаты поиска</h2>
    {% if search_results %}
        <ul>
            {% for post in search_results %}
                <li>
                    <h3><a href="{% url 'news:news_detail' post.pk %}">{{ post.title }}</a></h3>
                    <p>Автор: {{ post.author}}</p>
                    <p>Дата публикации: {{ post.created_at }}</p>
                    <p>{{ post.content }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Ничего не найдено.</p>
    {% endif %}
{% endblock %}